on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release project to Homebrew tap
        uses: Justintime50/homebrew-releaser@v3
        with:
          homebrew_owner: anussel5559
          homebrew_tap: homebrew-tap

          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          commit_owner: anussel5559
          commit_email: alex.nussel@gmail.com

          install: 'bin.install "pw"'

          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: false

          skip_commit: true
          debug: true
